version: '3.5'
# networking
# volumes
services:
  fx-bot:
    image: "fxlabs/bot:latest"
    #autodestroy: ALWAYS
    #autorestart: ON_FAILURE
    #autoredeploy: true
    #target_num_containers: 2
    #sequential_deployment: true
    #deployment_strategy: high_availability
    deploy:
      replicas: 1
      placement:
        constraints: [node.role == manager]
      update_config:
        parallelism: 2
        delay: 10s
        order: stop-first
    environment:
      # Fx-Connection
      - FX_HOST=${RABBITMQ_HOST}
      - FX_PORT=${RABBITMQ_PORT}
      - FX_USERNAME=${RABBITMQ_DEFAULT_USER}
      - FX_PASSWORD=${RABBITMQ_DEFAULT_PASS}
      - FX_KEY=fx-default-region
    logging:
      driver: syslog
      options:
        tag: "{{.Name}}/{{.ID}}"

    # inject rabbit-host, port, vhost, user-bot, user-bot-pass

  fx-mail-bot:
    image: "fxlabs/mail-bot:latest"
    #autodestroy: ALWAYS
    #autorestart: ON_FAILURE
    #autoredeploy: true
    #target_num_containers: 2
    #sequential_deployment: true
    #deployment_strategy: high_availability
    deploy:
      replicas: 1
      placement:
        constraints: [node.role == manager]
      update_config:
        parallelism: 2
        delay: 10s
        order: stop-first
    environment:
      # Fx-Connection
      - FX_HOST=${RABBITMQ_HOST}
      - FX_PORT=${RABBITMQ_PORT}
      - FX_USERNAME=${RABBITMQ_DEFAULT_USER}
      - FX_PASSWORD=${RABBITMQ_DEFAULT_PASS}
    logging:
      driver: syslog
      options:
        tag: "{{.Name}}/{{.ID}}"

    # inject rabbit-host, port, vhost, user-mail, user-mail-pass

  fx-vc-git-skill-bot:
    image: "fxlabs/vc-git-skill-bot:latest"
    #autodestroy: ALWAYS
    #autorestart: ON_FAILURE
    #autoredeploy: true
    #target_num_containers: 2
    #sequential_deployment: true
    #deployment_strategy: high_availability
    deploy:
      replicas: 1
      placement:
        constraints: [node.role == manager]
      update_config:
        parallelism: 2
        delay: 10s
        order: stop-first
    environment:
      # RabbitMQ
      - FX_HOST=${RABBITMQ_HOST}
      - FX_PORT=${RABBITMQ_PORT}
      - FX_USERNAME=${RABBITMQ_DEFAULT_USER}
      - FX_PASSWORD=${RABBITMQ_DEFAULT_PASS}
      - FX_KEY=fx-gaas
    logging:
      driver: syslog
      options:
        tag: "{{.Name}}/{{.ID}}"

    # inject rabbit-host, port, vhost, user-sync, user-sync-pass
